import "./globals.css";
import "../../public/fonts/fonts.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Muddasser Khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className="font-urbanist">{children}</body>
    </html>
  );
}